/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UTS;

/**
 *
 * @author HP
 */
public class Restoran extends javax.swing.JFrame {

    /**
     * Creates new form Restoran
     */
    public Restoran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lalapanikan = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hargaikan = new javax.swing.JTextField();
        jumlahikan = new javax.swing.JTextField();
        totalikan = new javax.swing.JTextField();
        lalapanayam = new javax.swing.JCheckBox();
        ayamkrispy = new javax.swing.JCheckBox();
        ayambakar = new javax.swing.JCheckBox();
        hargaayam = new javax.swing.JTextField();
        hargaayamkrispy = new javax.swing.JTextField();
        hargaayambakar = new javax.swing.JTextField();
        jumlahayam = new javax.swing.JTextField();
        jumlahayamkrispy = new javax.swing.JTextField();
        jumlahayambakar = new javax.swing.JTextField();
        totalayam = new javax.swing.JTextField();
        totalayamkrispy = new javax.swing.JTextField();
        totalayambakar = new javax.swing.JTextField();
        HITUNG = new javax.swing.JButton();
        totalfull = new javax.swing.JButton();
        bayartotalfull = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Aplikasi Restoran");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Menu Makanan");

        lalapanikan.setText("Lalapan Ikan");
        lalapanikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lalapanikanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Harga");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Jumlah");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Total");

        hargaikan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaikan.setText("0");

        jumlahikan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahikan.setText("0");

        totalikan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalikan.setText("0");

        lalapanayam.setText("Lalapan Ayam");
        lalapanayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lalapanayamActionPerformed(evt);
            }
        });

        ayamkrispy.setText("Ayam Krispy");
        ayamkrispy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayamkrispyActionPerformed(evt);
            }
        });

        ayambakar.setText("Ayam Bakar");
        ayambakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayambakarActionPerformed(evt);
            }
        });

        hargaayam.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaayam.setText("0");

        hargaayamkrispy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaayamkrispy.setText("0");

        hargaayambakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaayambakar.setText("0");

        jumlahayam.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahayam.setText("0");

        jumlahayamkrispy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahayamkrispy.setText("0");

        jumlahayambakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahayambakar.setText("0");

        totalayam.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalayam.setText("0");

        totalayamkrispy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalayamkrispy.setText("0");

        totalayambakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalayambakar.setText("0");
        totalayambakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalayambakarActionPerformed(evt);
            }
        });

        HITUNG.setText("HITUNG");
        HITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HITUNGActionPerformed(evt);
            }
        });

        totalfull.setText("TOTAL");

        bayartotalfull.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bayartotalfull.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lalapanikan)
                            .addComponent(jLabel2)))
                    .addComponent(ayamkrispy)
                    .addComponent(ayambakar)
                    .addComponent(lalapanayam, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel3))
                        .addComponent(hargaikan, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                        .addComponent(hargaayam)
                        .addComponent(hargaayamkrispy)
                        .addComponent(hargaayambakar))
                    .addComponent(HITUNG))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4))
                    .addComponent(totalfull)
                    .addComponent(jumlahikan, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jumlahayam)
                    .addComponent(jumlahayamkrispy)
                    .addComponent(jumlahayambakar))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5))
                    .addComponent(totalikan, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(totalayam)
                    .addComponent(totalayamkrispy)
                    .addComponent(totalayambakar)
                    .addComponent(bayartotalfull))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lalapanikan)
                    .addComponent(hargaikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lalapanayam)
                    .addComponent(hargaayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ayamkrispy)
                    .addComponent(hargaayamkrispy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahayamkrispy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalayamkrispy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ayambakar)
                    .addComponent(hargaayambakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahayambakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalayambakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HITUNG)
                    .addComponent(totalfull)
                    .addComponent(bayartotalfull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalayambakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalayambakarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalayambakarActionPerformed

    private void lalapanikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lalapanikanActionPerformed
        // kode untuk cekboks lalapan ikan
        if (lalapanikan.isSelected()){
            hargaikan.setEnabled(true);
            jumlahikan.setEnabled(true);
            totalikan.setEnabled(true);
        }else{
            hargaikan.setEnabled(false);
            jumlahikan.setEnabled(false);
            totalikan.setEnabled(false);
        }
    }//GEN-LAST:event_lalapanikanActionPerformed

    private void lalapanayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lalapanayamActionPerformed
        // TODO add your handling code here:
         if (lalapanayam.isSelected()){
            hargaayam.setEnabled(true);
            jumlahayam.setEnabled(true);
            totalayam.setEnabled(true);
        }else{
            hargaayam.setEnabled(false);
            jumlahayam.setEnabled(false);
            totalayam.setEnabled(false);
        }
    }//GEN-LAST:event_lalapanayamActionPerformed

    private void ayamkrispyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayamkrispyActionPerformed
        // TODO add your handling code here:
        if (ayamkrispy.isSelected()){
            hargaayamkrispy.setEnabled(true);
            jumlahayamkrispy.setEnabled(true);
            totalayamkrispy.setEnabled(true);
        }else{
            hargaayamkrispy.setEnabled(false);
            jumlahayamkrispy.setEnabled(false);
            totalayamkrispy.setEnabled(false);
        }
    }//GEN-LAST:event_ayamkrispyActionPerformed

    private void ayambakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayambakarActionPerformed
        // TODO add your handling code here:
         if (ayambakar.isSelected()){
            hargaayambakar.setEnabled(true);
            jumlahayambakar.setEnabled(true);
            totalayambakar.setEnabled(true);
        }else{
            hargaayambakar.setEnabled(false);
            jumlahayambakar.setEnabled(false);
            totalayambakar.setEnabled(false);
        }
    }//GEN-LAST:event_ayambakarActionPerformed

    private void HITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HITUNGActionPerformed
        // TODO add your handling code here:
        int hargaIkan = Integer.parseInt(hargaikan.getText());
        int jumlahIkan = Integer.parseInt(jumlahikan.getText());
        totalikan.setText(Integer.toString(jumlahIkan * hargaIkan));

        int hargaAyam = Integer.parseInt(hargaayam.getText());
        int jumlahAyam = Integer.parseInt(jumlahayam.getText());
        totalayam.setText(Integer.toString(jumlahAyam * hargaAyam));

        int hargaAyamKrispy = Integer.parseInt(hargaayamkrispy.getText());
        int jumlahAyamKrispy = Integer.parseInt(jumlahayamkrispy.getText());
        totalayamkrispy.setText(Integer.toString(jumlahAyamKrispy * hargaAyamKrispy));

        int hargaAyamBakar = Integer.parseInt(hargaayambakar.getText());
        int jumlahAyamBakar = Integer.parseInt(jumlahayambakar.getText());
        totalayambakar.setText(Integer.toString(jumlahAyamBakar * hargaAyamBakar));


        int TOTAL1 =Integer.parseInt(totalikan.getText());
        int TOTAL2 =Integer.parseInt(totalayam.getText());
        int TOTAL3 =Integer.parseInt(totalayamkrispy.getText());
        int TOTAL4 =Integer.parseInt(totalayambakar.getText());
        int Full = TOTAL1 + TOTAL2 + TOTAL3 + TOTAL4;
        totalfull.setText("Rp." + Full + ",00");
        
    }//GEN-LAST:event_HITUNGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restoran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HITUNG;
    private javax.swing.JCheckBox ayambakar;
    private javax.swing.JCheckBox ayamkrispy;
    private javax.swing.JTextField bayartotalfull;
    private javax.swing.JTextField hargaayam;
    private javax.swing.JTextField hargaayambakar;
    private javax.swing.JTextField hargaayamkrispy;
    private javax.swing.JTextField hargaikan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jumlahayam;
    private javax.swing.JTextField jumlahayambakar;
    private javax.swing.JTextField jumlahayamkrispy;
    private javax.swing.JTextField jumlahikan;
    private javax.swing.JCheckBox lalapanayam;
    private javax.swing.JCheckBox lalapanikan;
    private javax.swing.JTextField totalayam;
    private javax.swing.JTextField totalayambakar;
    private javax.swing.JTextField totalayamkrispy;
    private javax.swing.JButton totalfull;
    private javax.swing.JTextField totalikan;
    // End of variables declaration//GEN-END:variables
}
